### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by totalnooob** [ashstrahle/PowerShellBlazor#2]
Hello,

so how can it be installed? Its visual studio required?

Thanks

**Comment by ashstrahle** [comment]
You'll just need dotnet 7 (& git) installed. git clone this repo, go to PowerShellBlazor folder within the repo and execute: 

```dotnet run```

Look for a line similar to this and go to that url: 

<img width="349" alt="image" src="https://user-images.githubusercontent.com/54830016/234444302-6b16c832-3320-4086-a8c4-0b52750db596.png">
