### ISSUE TITLE
how to deploy standalone or through iis or nginx

### ISSUE THREAD

**Issue by ericxin1982** [ashstrahle/PowerShellBlazor#5]
Hi @ashstrahle 

Thanks for creating this great tool.
Just wondering how to deploy this.

Thanks
Eric Xin

**Comment by ashstrahle** [comment]
Hi @ericxin1982 

I'd normally deploy through Visual Studio, however I no longer have access to it, and Visual Studio is no longer supported on Mac. You can compile/deploy doing something like this:

```dotnet publish --runtime osx-arm64 --configuration Release --self-contained true -p:PublishSingleFile=true```

```dotnet run```

**Comment by ericxin1982** [comment]
Got it, thanks.
